# Changed the name to be more descriptive
name: Code Linters

on: [push]

jobs:
  # Renamed this job for clarity
  pylint:
    name: Lint Python Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      # Updated to a more current version of the setup-python action
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r backend/requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
        
  eslint:
    name: Lint React App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: "20.19.4"
        cache: 'npm'
        # Point cache to the correct lock file location
        cache-dependency-path: ./cory/package-lock.json

    - name: Install dependencies
      # This command runs inside the 'frontend' folder
      working-directory: ./cory
      run: npm ci

    - name: Run ESLint
      # This command also runs inside the 'frontend' folder
      working-directory: ./cory
      run: npm run lint